/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author giliarde
 */
public class Login extends javax.swing.JInternalFrame {
    
    
  
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLogin = new javax.swing.JPanel();
        jLTituloLogin = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLUsuario = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jBEntrar = new javax.swing.JButton();
        jPSenha = new javax.swing.JPasswordField();
        jPBarraCarregando = new javax.swing.JProgressBar();
        jLCarregando = new javax.swing.JLabel();

        jPLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLTituloLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloLogin.setText("Sistema de Urna Eletrônica");
        jLTituloLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPLoginLayout = new javax.swing.GroupLayout(jPLogin);
        jPLogin.setLayout(jPLoginLayout);
        jPLoginLayout.setHorizontalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLTituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        jPLoginLayout.setVerticalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloLogin)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTUsuario.setText("admin");
        jTUsuario.setPreferredSize(new java.awt.Dimension(30, 20));

        jLUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLUsuario.setText("Usuario :");

        jLSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLSenha.setText("Senha :");

        jBEntrar.setText("Entrar");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLUsuario)
                                        .addGap(0, 0, 0))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLSenha)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(jPSenha)
                                    .addComponent(jPBarraCarregando, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(51, 51, 51)
                        .addComponent(jBEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLUsuario)
                            .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPSenha)
                                .addGap(1, 1, 1))))
                    .addComponent(jBEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPBarraCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        // TODO add your handling code here:
        String usuario = jTUsuario.getText();
        String senha = String.valueOf(jPSenha.getPassword());
        
        
        
        
        if("admin".equals(usuario) && "admin".equals(senha)){
            
            new Thread(){
                public void run(){
                
                    for (int i = 0; i < 101; i++) {
                        
                        try {
                            sleep(100);
                            jPBarraCarregando.setValue(i);
                            
                            if (jPBarraCarregando.getValue()<=25) {
                                jLCarregando.setText("Carregando Sistema...");
                            }else if (jPBarraCarregando.getValue()<=25) {
                                jLCarregando.setText("Carregando Banco de Dados...");
                            }else if (jPBarraCarregando.getValue()<=50) {
                                jLCarregando.setText("Efetuando Leitura das Tabelas...");
                            }else if (jPBarraCarregando.getValue()<=75) {
                                jLCarregando.setText("Aguarde... O sistema esta Sendo Iniciado!!!");
                                
                                
                            }
                            
                        } catch (Exception e) {
                        }
                        
                    }
                    
                    
                    Login.this.dispose();
                    
                }
                            
                                
                                
            }.start();        
            
            
            
        
      }else { 
            JOptionPane.showMessageDialog(null,"Login ou Senha incorretos","Sistema Urna Eletrônica",JOptionPane.PLAIN_MESSAGE);
            jPSenha.setText("");
            
            
            
        			}
    }//GEN-LAST:event_jBEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JLabel jLCarregando;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLTituloLogin;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JProgressBar jPBarraCarregando;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
