/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CandidatoControlle;
import controller.VotoControlle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;
import javax.swing.Timer;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.net.URL;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author giliarde
 */
public class MenuView extends javax.swing.JFrame {

     private CandidatoControlle candidatoController;
     private VotoControlle votoController;    
     
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        this.candidatoController = new CandidatoControlle();
        this.votoController = new VotoControlle();        

        Login lg = new Login();

        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);        

        initComponents();
        this.jBPrincipal.add(lg);                
        lg.setVisible(true);        
        
        try {
            lg.setMaximum(true);
       
           lg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
           
        } catch (PropertyVetoException ex) {
           Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    private void BuscarCandidato(){
           String numero = jTDigitoUM.getText() + jTDigitoDOIS.getText();
            int valor = Integer.parseInt(numero);
            
           votoController.candidato = candidatoController.BuscarCandidato(valor);
           
           if (votoController.candidato != null) {
            jTNome.setText(votoController.candidato.getNome());
            jTCargo.setText(votoController.candidato.getCargo());
            
            ImageIcon imagem = new ImageIcon(votoController.candidato.getFoto());
            
            jLFoto.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLFoto.getWidth(), jLFoto.getHeight(), Image.SCALE_DEFAULT)));
           }
           
    }
    
    private void LimparCampos(){
        jTDigitoUM.setText("");
        jTDigitoDOIS.setText("");
        jTCargo.setText("");
        jTNome.setText("");
        jLFoto.setIcon(null);
    }
    
    private void FinalizaVoto(){
              Toolkit  toolkit = Toolkit.getDefaultToolkit();
              Dimension screensize = toolkit.getScreenSize();
              this.LiberarEleitor.setBounds(0, 0, screensize.width, screensize.height);
              this.LiberarEleitor.setVisible(true); 
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LiberarEleitor = new javax.swing.JDialog();
        jPFim = new javax.swing.JPanel();
        jLFim = new javax.swing.JLabel();
        jSAreaRestrita = new javax.swing.JSeparator();
        jLNovoEleitor = new javax.swing.JButton();
        jLResultadoFinal = new javax.swing.JButton();
        jLCodigoSeguranca = new javax.swing.JLabel();
        jTInserirNovoEleitor = new javax.swing.JTextField();
        jBSair1 = new javax.swing.JButton();
        jDUrna = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTNome = new javax.swing.JTextField();
        jLFoto = new javax.swing.JLabel();
        jTDigitoDOIS = new javax.swing.JTextField();
        jTDigitoUM = new javax.swing.JTextField();
        jTCargo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBTRES = new javax.swing.JButton();
        jBUM = new javax.swing.JButton();
        jBDOIS = new javax.swing.JButton();
        jBQUANTRO = new javax.swing.JButton();
        jBSETE = new javax.swing.JButton();
        jBCINCO = new javax.swing.JButton();
        jBSEIS = new javax.swing.JButton();
        jBOITO = new javax.swing.JButton();
        jBBRANCO = new javax.swing.JButton();
        jBNOVE = new javax.swing.JButton();
        jBZERO = new javax.swing.JButton();
        jBCONFIRMAR = new javax.swing.JButton();
        jBCANCELAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLDataHora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBPrincipal = new javax.swing.JDesktopPane();
        CadastrarCandidato = new javax.swing.JButton();
        jBLimparBase = new javax.swing.JButton();
        jBRelatorio = new javax.swing.JButton();
        jBUrnaElectronica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBSair = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        LiberarEleitor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        LiberarEleitor.setTitle("Liberação de Urna Eletronica");

        jLFim.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        jLFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFim.setText("FIM");
        jLFim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPFimLayout = new javax.swing.GroupLayout(jPFim);
        jPFim.setLayout(jPFimLayout);
        jPFimLayout.setHorizontalGroup(
            jPFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFimLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLFim, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFimLayout.setVerticalGroup(
            jPFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFim, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSAreaRestrita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area Restrita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLNovoEleitor.setText("Novo Eleitor");
        jLNovoEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLNovoEleitorActionPerformed(evt);
            }
        });

        jLResultadoFinal.setText("Resultado Final");
        jLResultadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLResultadoFinalActionPerformed(evt);
            }
        });

        jLCodigoSeguranca.setText("Codigo de Segurança");

        jBSair1.setText("Sair");
        jBSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LiberarEleitorLayout = new javax.swing.GroupLayout(LiberarEleitor.getContentPane());
        LiberarEleitor.getContentPane().setLayout(LiberarEleitorLayout);
        LiberarEleitorLayout.setHorizontalGroup(
            LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LiberarEleitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LiberarEleitorLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jSAreaRestrita, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LiberarEleitorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTInserirNovoEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCodigoSeguranca))
                .addGap(65, 65, 65)
                .addGroup(LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair1)
                    .addComponent(jLResultadoFinal)
                    .addComponent(jLNovoEleitor))
                .addGap(331, 331, 331))
        );
        LiberarEleitorLayout.setVerticalGroup(
            LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LiberarEleitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSAreaRestrita, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNovoEleitor)
                    .addComponent(jLCodigoSeguranca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LiberarEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLResultadoFinal)
                    .addComponent(jTInserirNovoEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSair1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LiberarEleitor.getAccessibleContext().setAccessibleParent(jBPrincipal);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));

        centro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        centro.setAutoscrolls(true);
        centro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTNome.setEditable(false);
        jTNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNome.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTNome)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTDigitoDOIS.setEditable(false);
        jTDigitoDOIS.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTDigitoDOIS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDigitoDOIS.setBorder(null);
        jTDigitoDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDigitoDOISActionPerformed(evt);
            }
        });

        jTDigitoUM.setEditable(false);
        jTDigitoUM.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTDigitoUM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDigitoUM.setBorder(null);

        jTCargo.setEditable(false);
        jTCargo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTCargo.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jBTRES.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBTRES.setText("3");
        jBTRES.setToolTipText("");
        jBTRES.setMaximumSize(new java.awt.Dimension(164, 65));
        jBTRES.setMinimumSize(new java.awt.Dimension(50, 65));
        jBTRES.setPreferredSize(new java.awt.Dimension(100, 50));
        jBTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRESActionPerformed(evt);
            }
        });

        jBUM.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBUM.setText("1");
        jBUM.setMaximumSize(new java.awt.Dimension(164, 65));
        jBUM.setMinimumSize(new java.awt.Dimension(50, 65));
        jBUM.setPreferredSize(new java.awt.Dimension(100, 50));
        jBUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUMActionPerformed(evt);
            }
        });

        jBDOIS.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBDOIS.setText("2");
        jBDOIS.setMaximumSize(new java.awt.Dimension(164, 65));
        jBDOIS.setMinimumSize(new java.awt.Dimension(50, 65));
        jBDOIS.setPreferredSize(new java.awt.Dimension(100, 50));
        jBDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDOISActionPerformed(evt);
            }
        });

        jBQUANTRO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBQUANTRO.setText("4");
        jBQUANTRO.setToolTipText("");
        jBQUANTRO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBQUANTRO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBQUANTRO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBQUANTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQUANTROActionPerformed(evt);
            }
        });

        jBSETE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBSETE.setText("7");
        jBSETE.setToolTipText("");
        jBSETE.setMaximumSize(new java.awt.Dimension(164, 65));
        jBSETE.setMinimumSize(new java.awt.Dimension(164, 65));
        jBSETE.setPreferredSize(new java.awt.Dimension(100, 50));
        jBSETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSETEActionPerformed(evt);
            }
        });

        jBCINCO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCINCO.setText("5");
        jBCINCO.setToolTipText("");
        jBCINCO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBCINCO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBCINCO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCINCOActionPerformed(evt);
            }
        });

        jBSEIS.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBSEIS.setText("6");
        jBSEIS.setToolTipText("");
        jBSEIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSEIS.setMaximumSize(new java.awt.Dimension(164, 65));
        jBSEIS.setMinimumSize(new java.awt.Dimension(50, 65));
        jBSEIS.setPreferredSize(new java.awt.Dimension(100, 50));
        jBSEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSEISActionPerformed(evt);
            }
        });

        jBOITO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBOITO.setText("8");
        jBOITO.setToolTipText("");
        jBOITO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBOITO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBOITO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBOITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOITOActionPerformed(evt);
            }
        });

        jBBRANCO.setBackground(new java.awt.Color(255, 255, 255));
        jBBRANCO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBBRANCO.setText("BRANCO");
        jBBRANCO.setToolTipText("");
        jBBRANCO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBBRANCO.setMinimumSize(new java.awt.Dimension(164, 65));
        jBBRANCO.setPreferredSize(new java.awt.Dimension(164, 65));
        jBBRANCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBRANCOActionPerformed(evt);
            }
        });

        jBNOVE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBNOVE.setText("9");
        jBNOVE.setToolTipText("");
        jBNOVE.setMaximumSize(new java.awt.Dimension(164, 65));
        jBNOVE.setMinimumSize(new java.awt.Dimension(50, 65));
        jBNOVE.setPreferredSize(new java.awt.Dimension(100, 50));
        jBNOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNOVEActionPerformed(evt);
            }
        });

        jBZERO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBZERO.setText("0");
        jBZERO.setToolTipText("");
        jBZERO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBZERO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBZERO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZEROActionPerformed(evt);
            }
        });

        jBCONFIRMAR.setBackground(new java.awt.Color(0, 153, 51));
        jBCONFIRMAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCONFIRMAR.setText("CONFIRMA");
        jBCONFIRMAR.setToolTipText("");
        jBCONFIRMAR.setBorder(null);
        jBCONFIRMAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCONFIRMAR.setMaximumSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.setMinimumSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.setPreferredSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCONFIRMARActionPerformed(evt);
            }
        });

        jBCANCELAR.setBackground(new java.awt.Color(255, 0, 51));
        jBCANCELAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCANCELAR.setText("CORRIGE");
        jBCANCELAR.setToolTipText("");
        jBCANCELAR.setMaximumSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.setMinimumSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.setPreferredSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jBBRANCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jBCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCONFIRMAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBQUANTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBZERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBCINCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBSEIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBDOIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBTRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBOITO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBNOVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBUM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBQUANTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOITO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBZERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBRANCO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/voto.png"))); // NOI18N

        jLDataHora.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setText("Eleitoral");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel5.setText("Justiça");

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jTDigitoUM, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTDigitoDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTCargo))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(centroLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centroLayout.createSequentialGroup()
                    .addContainerGap(818, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103)))
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDigitoUM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDigitoDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(centroLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(centroLayout.createSequentialGroup()
                                .addComponent(jLDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centroLayout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDUrnaLayout = new javax.swing.GroupLayout(jDUrna.getContentPane());
        jDUrna.getContentPane().setLayout(jDUrnaLayout);
        jDUrnaLayout.setHorizontalGroup(
            jDUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(jDUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDUrnaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDUrnaLayout.setVerticalGroup(
            jDUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(jDUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDUrnaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CadastrarCandidato.setText("Cadastrar Candidato");
        CadastrarCandidato.setToolTipText("");
        CadastrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarCandidatoActionPerformed(evt);
            }
        });
        jBPrincipal.add(CadastrarCandidato);
        CadastrarCandidato.setBounds(70, 430, 280, 40);

        jBLimparBase.setText("Limpar Base de Dados");
        jBLimparBase.setToolTipText("");
        jBLimparBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparBaseActionPerformed(evt);
            }
        });
        jBPrincipal.add(jBLimparBase);
        jBLimparBase.setBounds(70, 500, 280, 40);

        jBRelatorio.setText("Relatório");
        jBRelatorio.setToolTipText("");
        jBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioActionPerformed(evt);
            }
        });
        jBPrincipal.add(jBRelatorio);
        jBRelatorio.setBounds(70, 360, 130, 40);

        jBUrnaElectronica.setText("Urna");
        jBUrnaElectronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUrnaElectronicaActionPerformed(evt);
            }
        });
        jBPrincipal.add(jBUrnaElectronica);
        jBUrnaElectronica.setBounds(220, 360, 130, 40);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+3));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("dataSistema");
        jBPrincipal.add(jLabel1);
        jLabel1.setBounds(560, 650, 90, 20);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+3));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("hora");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPrincipal.add(jLabel2);
        jLabel2.setBounds(650, 650, 80, 20);

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        jBPrincipal.add(jBSair);
        jBSair.setBounds(270, 563, 80, 40);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void CadastrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarCandidatoActionPerformed
        // TODO add your handling code here:
        
        CadastrarCandidato telaCadastrar = new CadastrarCandidato();
        this.jBPrincipal.add(telaCadastrar);
        telaCadastrar.setVisible(true);
    }//GEN-LAST:event_CadastrarCandidatoActionPerformed

    private void jBUrnaElectronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUrnaElectronicaActionPerformed
        // TODO add your handling code here:
        Toolkit  toolkit = Toolkit.getDefaultToolkit();
        Dimension screensize = toolkit.getScreenSize();
        this.jDUrna.setBounds(0, 0, screensize.width, screensize.height);
        this.jDUrna.setVisible(true);
        
    }//GEN-LAST:event_jBUrnaElectronicaActionPerformed

    private void jBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioActionPerformed
        // TODO add your handling code here:
        Relatorio relatorio = new Relatorio();      
        this.jBPrincipal.add(relatorio);  
        relatorio.setSize(885, 549);      
        relatorio.setVisible(true);
        
    }//GEN-LAST:event_jBRelatorioActionPerformed
   
    private void jBLimparBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparBaseActionPerformed
        // TODO add your handling code here:
        votoController.Limpar();
        candidatoController.Limpar();        
    }//GEN-LAST:event_jBLimparBaseActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Date dataUrna = new Date();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
       jLabel1.setText(formato.format(dataUrna));
       
       Timer horaUrna = new Timer(1000, new hora());
       horaUrna.start();
    }//GEN-LAST:event_formWindowOpened

    private void jBSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSair1ActionPerformed
        // TODO add your handling code here:
       this.LiberarEleitor.dispose();        
    }//GEN-LAST:event_jBSair1ActionPerformed

    private void jTDigitoDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDigitoDOISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDigitoDOISActionPerformed

    private void jBTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRESActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("3");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("3");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBTRESActionPerformed

    private void jBUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUMActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("1");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("1");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBUMActionPerformed

    private void jBDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDOISActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("2");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("2");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBDOISActionPerformed

    private void jBQUANTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQUANTROActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText())|| jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("4");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("4");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBQUANTROActionPerformed

    private void jBSETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSETEActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("7");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("7");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBSETEActionPerformed

    private void jBCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCINCOActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("5");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("5");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBCINCOActionPerformed

    private void jBSEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSEISActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("6");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("6");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBSEISActionPerformed

    private void jBOITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOITOActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("8");
            BuscarCandidato();
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("8");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBOITOActionPerformed

    private void jBBRANCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBRANCOActionPerformed
        // TODO add your handling code here:

        jTDigitoUM.setText("0");
        jTDigitoDOIS.setText("0");
        jTNome.setText("VOTO BRANCO");

        votoController.voto.setValorVoto(00);
        votoController.voto.setDataVoto(Calendar.getInstance());
        votoController.candidato = null;
        
    }//GEN-LAST:event_jBBRANCOActionPerformed

    private void jBNOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNOVEActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("9");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("9");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBNOVEActionPerformed

    private void jBZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZEROActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("0");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
                jTDigitoDOIS.setText("0");
                BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBZEROActionPerformed

    
     private void TocarMusica(){
         try {
       
        URL url = this.getClass().getResource("/view/Sound.wav");
         AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
         
         Clip clip = AudioSystem.getClip();
         
         clip.open(audioIn);
         clip.start();
      } catch (UnsupportedAudioFileException e) {
         e.printStackTrace();
      } catch (IOException e) {
         e.printStackTrace();
      } catch (LineUnavailableException e) {
         e.printStackTrace();
      }
    }
    
    private void jBCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCONFIRMARActionPerformed
     
        if ("".equals(jTDigitoUM.getText()) || "".equals(jTDigitoDOIS.getText())) {
            JOptionPane.showMessageDialog(this, "Voto invalido, preencha o número do candidato!");
        }else{
            String numero = jTDigitoUM.getText() + jTDigitoDOIS.getText();
            int valor = Integer.parseInt(numero);

            votoController.candidato = candidatoController.BuscarCandidato(valor);

            if (votoController.candidato == null && "VOTO BRANCO".equals(jTNome.getText())) {
                // voto 0 significa voto Branco
                valor = 0;
               
            }else{
             //valor 1 significa voto nulo
                valor = 1;
            }
            votoController.voto.setValorVoto(valor);
            votoController.voto.setDataVoto(Calendar.getInstance());
            votoController.Votar();
            LimparCampos();
            FinalizaVoto();
             TocarMusica();
            this.jDUrna.dispose();
        }
    }//GEN-LAST:event_jBCONFIRMARActionPerformed

    private void jBCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCANCELARActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_jBCANCELARActionPerformed

    private void jLResultadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLResultadoFinalActionPerformed
        // TODO add your handling code here:
          Relatorio relatorio = new Relatorio();      
        this.jBPrincipal.add(relatorio);
        relatorio.setSize(885, 549);      
        relatorio.setVisible(true);
    }//GEN-LAST:event_jLResultadoFinalActionPerformed

    private void jLNovoEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLNovoEleitorActionPerformed
              
        if(jTInserirNovoEleitor.getText().equals("admin")){
              jTInserirNovoEleitor.setText("");             
              Toolkit  toolkit = Toolkit.getDefaultToolkit();
              Dimension screensize = toolkit.getScreenSize();
              this.jDUrna.setBounds(0, 0, screensize.width, screensize.height);
              this.jDUrna.setVisible(true);
              this.LiberarEleitor.dispose();
        }else{
            jTInserirNovoEleitor.setText("");
            JOptionPane.showMessageDialog(null, "Informe um código de Admistrador valido!");
        }
    }//GEN-LAST:event_jLNovoEleitorActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarCandidato;
    private javax.swing.JDialog LiberarEleitor;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel centro;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jBBRANCO;
    private javax.swing.JButton jBCANCELAR;
    private javax.swing.JButton jBCINCO;
    private javax.swing.JButton jBCONFIRMAR;
    private javax.swing.JButton jBDOIS;
    private javax.swing.JButton jBLimparBase;
    private javax.swing.JButton jBNOVE;
    private javax.swing.JButton jBOITO;
    private javax.swing.JDesktopPane jBPrincipal;
    private javax.swing.JButton jBQUANTRO;
    private javax.swing.JButton jBRelatorio;
    private javax.swing.JButton jBSEIS;
    private javax.swing.JButton jBSETE;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSair1;
    private javax.swing.JButton jBTRES;
    private javax.swing.JButton jBUM;
    private javax.swing.JButton jBUrnaElectronica;
    private javax.swing.JButton jBZERO;
    private javax.swing.JDialog jDUrna;
    private javax.swing.JLabel jLCodigoSeguranca;
    private javax.swing.JLabel jLDataHora;
    private javax.swing.JLabel jLFim;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JButton jLNovoEleitor;
    private javax.swing.JButton jLResultadoFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPFim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSAreaRestrita;
    private javax.swing.JTextField jTCargo;
    private javax.swing.JTextField jTDigitoDOIS;
    private javax.swing.JTextField jTDigitoUM;
    private javax.swing.JTextField jTInserirNovoEleitor;
    private javax.swing.JTextField jTNome;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
class hora implements ActionListener{
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        jLabel2.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        
    }
 }
}
