/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.CandidatoControlle;
import controller.VotoControlle;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author giliarde
 */
public class Relatorio extends javax.swing.JInternalFrame {

     private CandidatoControlle candidatoController;
     private VotoControlle votoController;
    
    /** Creates new form Relatorio */
    public Relatorio() {
        this.candidatoController = new CandidatoControlle();
        this.votoController = new VotoControlle();
         
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) jTResultado.getModel();
        jTResultado.setRowSorter(new TableRowSorter(modelo));
        ResultadoEleicao();
    }
    
    private void ResultadoEleicao(){
           DefaultTableModel modelo = (DefaultTableModel) jTResultado.getModel();
    
         candidatoController.BuscarTodos().forEach((c) -> {
             modelo.addRow(new Object[]{
                 c.getNome(),
                 c.getNumero(),                 
                 votoController.ContarVotos(c.getNumero())
             });
        });
       
        jTVotosBrancos.setText(String.valueOf(votoController.ContarVotosBrancos()));
        jTVotosNulos.setText(String.valueOf(votoController.ContarVotosNulos()));
        jTVotosValidos.setText(String.valueOf(votoController.ContarVotosValidos()));
        jTEleitores.setText(String.valueOf(votoController.ContarEleitores()));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPRelatorioVotacao = new javax.swing.JPanel();
        jTVotosBrancos = new javax.swing.JTextField();
        jTVotosNulos = new javax.swing.JTextField();
        jTVotosValidos = new javax.swing.JTextField();
        jTEleitores = new javax.swing.JTextField();
        jBSair = new javax.swing.JButton();
        jLVotosBrancos = new javax.swing.JLabel();
        jLVotosNulos = new javax.swing.JLabel();
        jLVotosValidos = new javax.swing.JLabel();
        jLEleitores = new javax.swing.JLabel();
        jPTituloRelatorio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSPResultado = new javax.swing.JScrollPane();
        jTResultado = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jPRelatorioVotacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPRelatorioVotacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTEleitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEleitoresActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLVotosBrancos.setText("Brancos");

        jLVotosNulos.setText("Nulos");

        jLVotosValidos.setText("Validos");

        jLEleitores.setText("Eleitores");

        jPTituloRelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Relatorio das Eleições");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPTituloRelatorioLayout = new javax.swing.GroupLayout(jPTituloRelatorio);
        jPTituloRelatorio.setLayout(jPTituloRelatorioLayout);
        jPTituloRelatorioLayout.setHorizontalGroup(
            jPTituloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloRelatorioLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(334, 334, 334))
        );
        jPTituloRelatorioLayout.setVerticalGroup(
            jPTituloRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloRelatorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jTResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Candidado", "Legenda", "Quant. Votos"
            }
        ));
        jSPResultado.setViewportView(jTResultado);

        javax.swing.GroupLayout jPRelatorioVotacaoLayout = new javax.swing.GroupLayout(jPRelatorioVotacao);
        jPRelatorioVotacao.setLayout(jPRelatorioVotacaoLayout);
        jPRelatorioVotacaoLayout.setHorizontalGroup(
            jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTituloRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRelatorioVotacaoLayout.createSequentialGroup()
                                .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                                        .addComponent(jLVotosBrancos)
                                        .addGap(3, 3, 3))
                                    .addComponent(jLEleitores)
                                    .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLVotosNulos)
                                        .addComponent(jLVotosValidos)))
                                .addGap(18, 18, 18)
                                .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTEleitores, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jTVotosNulos, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jTVotosBrancos)
                                    .addComponent(jTVotosValidos)))
                            .addComponent(jBSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPRelatorioVotacaoLayout.setVerticalGroup(
            jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPTituloRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPRelatorioVotacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLVotosBrancos)
                            .addComponent(jTVotosBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLVotosNulos)
                            .addComponent(jTVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTVotosValidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLVotosValidos))
                        .addGap(20, 20, 20)
                        .addGroup(jPRelatorioVotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTEleitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEleitores))
                        .addGap(24, 24, 24)
                        .addComponent(jBSair)
                        .addGap(29, 29, 29))))
        );

        getContentPane().add(jPRelatorioVotacao);
        jPRelatorioVotacao.setBounds(10, 11, 850, 493);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTEleitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEleitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEleitoresActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLEleitores;
    private javax.swing.JLabel jLVotosBrancos;
    private javax.swing.JLabel jLVotosNulos;
    private javax.swing.JLabel jLVotosValidos;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPRelatorioVotacao;
    private javax.swing.JPanel jPTituloRelatorio;
    private javax.swing.JScrollPane jSPResultado;
    private javax.swing.JTextField jTEleitores;
    private javax.swing.JTable jTResultado;
    private javax.swing.JTextField jTVotosBrancos;
    private javax.swing.JTextField jTVotosNulos;
    private javax.swing.JTextField jTVotosValidos;
    // End of variables declaration//GEN-END:variables

}
