/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CandidatoControlle;
import controller.VotoControlle;
import java.awt.EventQueue;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto
 */
public class Urna extends javax.swing.JPanel {

     private CandidatoControlle candidatoController;
     private VotoControlle votoController;        
  

    /**
     * Creates new form Urna
     */
    public Urna() {
        this.candidatoController = new CandidatoControlle();
        this.votoController = new VotoControlle();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTNome = new javax.swing.JTextField();
        jLFoto = new javax.swing.JLabel();
        jTDigitoDOIS = new javax.swing.JTextField();
        jTDigitoUM = new javax.swing.JTextField();
        jTCargo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBTRES = new javax.swing.JButton();
        jBUM = new javax.swing.JButton();
        jBDOIS = new javax.swing.JButton();
        jBQUANTRO = new javax.swing.JButton();
        jBSETE = new javax.swing.JButton();
        jBCINCO = new javax.swing.JButton();
        jBSEIS = new javax.swing.JButton();
        jBOITO = new javax.swing.JButton();
        jBBRANCO = new javax.swing.JButton();
        jBNOVE = new javax.swing.JButton();
        jBZERO = new javax.swing.JButton();
        jBCONFIRMAR = new javax.swing.JButton();
        jBCANCELAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLDataHora = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(0, 0));

        centro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        centro.setAutoscrolls(true);
        centro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTNome.setEditable(false);
        jTNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNome.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTNome)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTDigitoDOIS.setEditable(false);
        jTDigitoDOIS.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTDigitoDOIS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDigitoDOIS.setBorder(null);
        jTDigitoDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDigitoDOISActionPerformed(evt);
            }
        });

        jTDigitoUM.setEditable(false);
        jTDigitoUM.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTDigitoUM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTDigitoUM.setBorder(null);

        jTCargo.setEditable(false);
        jTCargo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTCargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTCargo.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jBTRES.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBTRES.setText("3");
        jBTRES.setToolTipText("");
        jBTRES.setMaximumSize(new java.awt.Dimension(164, 65));
        jBTRES.setMinimumSize(new java.awt.Dimension(50, 65));
        jBTRES.setPreferredSize(new java.awt.Dimension(100, 50));
        jBTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRESActionPerformed(evt);
            }
        });

        jBUM.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBUM.setText("1");
        jBUM.setMaximumSize(new java.awt.Dimension(164, 65));
        jBUM.setMinimumSize(new java.awt.Dimension(50, 65));
        jBUM.setPreferredSize(new java.awt.Dimension(100, 50));
        jBUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUMActionPerformed(evt);
            }
        });

        jBDOIS.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBDOIS.setText("2");
        jBDOIS.setMaximumSize(new java.awt.Dimension(164, 65));
        jBDOIS.setMinimumSize(new java.awt.Dimension(50, 65));
        jBDOIS.setPreferredSize(new java.awt.Dimension(100, 50));
        jBDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDOISActionPerformed(evt);
            }
        });

        jBQUANTRO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBQUANTRO.setText("4");
        jBQUANTRO.setToolTipText("");
        jBQUANTRO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBQUANTRO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBQUANTRO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBQUANTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQUANTROActionPerformed(evt);
            }
        });

        jBSETE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBSETE.setText("7");
        jBSETE.setToolTipText("");
        jBSETE.setMaximumSize(new java.awt.Dimension(164, 65));
        jBSETE.setMinimumSize(new java.awt.Dimension(164, 65));
        jBSETE.setPreferredSize(new java.awt.Dimension(100, 50));
        jBSETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSETEActionPerformed(evt);
            }
        });

        jBCINCO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCINCO.setText("5");
        jBCINCO.setToolTipText("");
        jBCINCO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBCINCO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBCINCO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCINCOActionPerformed(evt);
            }
        });

        jBSEIS.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBSEIS.setText("6");
        jBSEIS.setToolTipText("");
        jBSEIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSEIS.setMaximumSize(new java.awt.Dimension(164, 65));
        jBSEIS.setMinimumSize(new java.awt.Dimension(50, 65));
        jBSEIS.setPreferredSize(new java.awt.Dimension(100, 50));
        jBSEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSEISActionPerformed(evt);
            }
        });

        jBOITO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBOITO.setText("8");
        jBOITO.setToolTipText("");
        jBOITO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBOITO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBOITO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBOITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOITOActionPerformed(evt);
            }
        });

        jBBRANCO.setBackground(new java.awt.Color(255, 255, 255));
        jBBRANCO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBBRANCO.setText("BRANCO");
        jBBRANCO.setToolTipText("");
        jBBRANCO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBBRANCO.setMinimumSize(new java.awt.Dimension(164, 65));
        jBBRANCO.setPreferredSize(new java.awt.Dimension(164, 65));
        jBBRANCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBRANCOActionPerformed(evt);
            }
        });

        jBNOVE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBNOVE.setText("9");
        jBNOVE.setToolTipText("");
        jBNOVE.setMaximumSize(new java.awt.Dimension(164, 65));
        jBNOVE.setMinimumSize(new java.awt.Dimension(50, 65));
        jBNOVE.setPreferredSize(new java.awt.Dimension(100, 50));
        jBNOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNOVEActionPerformed(evt);
            }
        });

        jBZERO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBZERO.setText("0");
        jBZERO.setToolTipText("");
        jBZERO.setMaximumSize(new java.awt.Dimension(164, 65));
        jBZERO.setMinimumSize(new java.awt.Dimension(50, 65));
        jBZERO.setPreferredSize(new java.awt.Dimension(100, 50));
        jBZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZEROActionPerformed(evt);
            }
        });

        jBCONFIRMAR.setBackground(new java.awt.Color(0, 153, 51));
        jBCONFIRMAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCONFIRMAR.setText("CONFIRMA");
        jBCONFIRMAR.setToolTipText("");
        jBCONFIRMAR.setBorder(null);
        jBCONFIRMAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCONFIRMAR.setMaximumSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.setMinimumSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.setPreferredSize(new java.awt.Dimension(164, 70));
        jBCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCONFIRMARActionPerformed(evt);
            }
        });

        jBCANCELAR.setBackground(new java.awt.Color(255, 0, 51));
        jBCANCELAR.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBCANCELAR.setText("CORRIGE");
        jBCANCELAR.setToolTipText("");
        jBCANCELAR.setMaximumSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.setMinimumSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.setPreferredSize(new java.awt.Dimension(164, 65));
        jBCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBBRANCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jBCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCONFIRMAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBQUANTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBZERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBCINCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBSEIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBDOIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBTRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBOITO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jBNOVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBUM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBQUANTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOITO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSETE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBZERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBRANCO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/voto.png"))); // NOI18N

        jLDataHora.setToolTipText("");

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jTDigitoUM, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTDigitoDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTCargo))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(106, 106, 106)
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDigitoUM, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDigitoDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centroLayout.createSequentialGroup()
                        .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jBUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUMActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("1");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("1"); 
              BuscarCandidato();
            }            
        }
    }//GEN-LAST:event_jBUMActionPerformed

    private void jBDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDOISActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("2");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("2");
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBDOISActionPerformed

    private void jBTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRESActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("3");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("3");
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBTRESActionPerformed

    private void jBQUANTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQUANTROActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText())|| jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("4");
        }else{
             if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("4");  
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBQUANTROActionPerformed

    private void jBCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCINCOActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("5");
        }else{
             if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("5");  
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBCINCOActionPerformed

    private void jBSEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSEISActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("6");
        }else{
             if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("6"); 
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBSEISActionPerformed

    private void jBSETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSETEActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("7");
        }else{
             if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("7");
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBSETEActionPerformed

    private void jBOITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOITOActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("8");
            BuscarCandidato();
        }else{
             if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("8");
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBOITOActionPerformed

    private void jBNOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNOVEActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("9");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("9");
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBNOVEActionPerformed

    private void jBZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZEROActionPerformed
        // TODO add your handling code here:
         if ("".equals(jTDigitoUM.getText()) || jTDigitoUM.getText().isEmpty()) {
            jTDigitoUM.setText("0");
        }else{
            if ("".equals(jTDigitoDOIS.getText()) || jTDigitoDOIS.getText().isEmpty()) {
              jTDigitoDOIS.setText("0"); 
              BuscarCandidato();
            }
        }
    }//GEN-LAST:event_jBZEROActionPerformed

    private void jBBRANCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBRANCOActionPerformed
        // TODO add your handling code here:
        
        jTDigitoUM.setText("0");
        jTDigitoDOIS.setText("0"); 
        
        votoController.voto.setValorVoto(00);
        votoController.voto.setDataVoto(Calendar.getInstance());
        votoController.candidato = null;
        votoController.Votar();
    }//GEN-LAST:event_jBBRANCOActionPerformed

    private void jBCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCONFIRMARActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTDigitoUM.getText()) || "".equals(jTDigitoDOIS.getText())) {
            JOptionPane.showMessageDialog(this, "Voto invalido, preencha o número do candidato!");
        }else{
            String numero = jTDigitoUM.getText() + jTDigitoDOIS.getText();
            int valor = Integer.parseInt(numero);
            
           votoController.candidato = candidatoController.BuscarCandidato(valor);
           
            if (votoController.candidato == null) { 
                //valor 1 significa voto nulo
                valor = 1;
            }
           votoController.voto.setValorVoto(valor);
           votoController.voto.setDataVoto(Calendar.getInstance());
           votoController.Votar();
           LimparCampos();
           LiberarNovoEleitor telaLiberaEleitor = new LiberarNovoEleitor();
           this.getParent().getParent().add(telaLiberaEleitor);
            try {
            telaLiberaEleitor.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
           telaLiberaEleitor.setVisible(true);
          
        }
        
    }//GEN-LAST:event_jBCONFIRMARActionPerformed

    private void BuscarCandidato(){
           String numero = jTDigitoUM.getText() + jTDigitoDOIS.getText();
            int valor = Integer.parseInt(numero);
            
           votoController.candidato = candidatoController.BuscarCandidato(valor);
           
           if (votoController.candidato != null) {
            jTNome.setText(votoController.candidato.getNome());
            jTCargo.setText(votoController.candidato.getCargo());
            
            ImageIcon imagem = new ImageIcon(votoController.candidato.getFoto());
            
            jLFoto.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLFoto.getWidth(), jLFoto.getHeight(), Image.SCALE_DEFAULT)));
           }
           
    } 
    
    private void LimparCampos(){
        jTDigitoUM.setText("");
        jTDigitoDOIS.setText("");
        jTCargo.setText("");
        jTNome.setText("");
        jLFoto.setIcon(null);
    }
    
    private void jBCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCANCELARActionPerformed
        // TODO add your handling code here:
        LimparCampos();        
    }//GEN-LAST:event_jBCANCELARActionPerformed

    private void jTDigitoDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDigitoDOISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDigitoDOISActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centro;
    private javax.swing.JButton jBBRANCO;
    private javax.swing.JButton jBCANCELAR;
    private javax.swing.JButton jBCINCO;
    private javax.swing.JButton jBCONFIRMAR;
    private javax.swing.JButton jBDOIS;
    private javax.swing.JButton jBNOVE;
    private javax.swing.JButton jBOITO;
    private javax.swing.JButton jBQUANTRO;
    private javax.swing.JButton jBSEIS;
    private javax.swing.JButton jBSETE;
    private javax.swing.JButton jBTRES;
    private javax.swing.JButton jBUM;
    private javax.swing.JButton jBZERO;
    private javax.swing.JLabel jLDataHora;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTCargo;
    private javax.swing.JTextField jTDigitoDOIS;
    private javax.swing.JTextField jTDigitoUM;
    private javax.swing.JTextField jTNome;
    // End of variables declaration//GEN-END:variables
}
